### ISSUE TITLE
Default Route

### ISSUE THREAD

**Issue by MattHeslington** [victoria-lo/photo-album#1]
Hi, 
 I have a feeling this may be a silly question, but how did you get 'npm start' to default to the '/photo-album' folder? I recreated this project using your code and thought it wasn't working because my npm-start defaulted to the normal localhost:3000, so the project looked like it wasn't working. However, if I manually go to /home' (the same as your '/photo-album' it works as your code does.
Cheers,
Matt

**Comment by victoria-lo** [comment]
On your command prompt, use the command 'cd  /folder_name' to change directory to the root folder. Then run 'npm install' and after that, 'npm start'.

**Comment by MattHeslington** [comment]
Sorry, you misunderstand me. On npm start, the server defaults to the photo-album folder. How do you do that?

![image](https://user-images.githubusercontent.com/8208896/93658076-045efc80-fa6b-11ea-927d-88bc2c0dc18c.png)

**Comment by victoria-lo** [comment]
Oh that's because I specified the route in the package.json, "homepage": "https://victoria.github.io/photo-album/" and in App.js, I have react-router with the Home component as the "/photo-album" route. So on localhost, it would default to localhost:3000/photo-album.
